### ISSUE TITLE
A question about the paper

### ISSUE THREAD

**Issue by richhh520** [ZHZisZZ/weak-to-strong-search#2]
Hi Dear author,

I am curious about how to derive Eq.13 from Eq.12?

Does V∗(s_t+1) = V∗(s_H,a_H)?

Thanks for your help.

**Comment by richhh520** [comment]
and why r(st,at) is ignored?

**Comment by ZHZisZZ** [comment]
> Does V∗(s_t+1) = V∗(s_H,a_H)?

I believe you are mostly correct, but there's a small typo above. In this MDP, we define s_t+1 = (s_t, a_t) (see paragraph 2 of Appendix A). Therefore V∗(s_H+1) =V*((S_H, a_H))

**Comment by richhh520** [comment]
So that if we substitude this into Eq. 10, we have r(st, at) + β log πref(at | st)=0 for a_t!=EOS? why is that?
![image](https://github.com/user-attachments/assets/d4113897-fdbc-4496-819c-155f3f15ecea)

**Comment by richhh520** [comment]
while in From r to q Eq.3, they define 
![image](https://github.com/user-attachments/assets/16ca59ab-f96a-41a5-954a-966087dffd7f)
How to explain their connection?

**Comment by ZHZisZZ** [comment]
I do not quite get this. "s_t+1 := s_t, a_t" does not mean "Q*(s_t, a_t) = V*(s_t+1)".

**Comment by ZHZisZZ** [comment]
The terms "Q" and "V" here are actually representing soft values. For more details, I recommend referring to the derivations provided in [Reinforcement Learning with Deep Energy-Based Policies](https://arxiv.org/pdf/1702.08165). If you have further questions or suggestions on how we can enhance our presentation, please feel free to reach out. Your input is always welcome!

**Comment by richhh520** [comment]
Sorry for the bothering! May I have your Wechat? My wechat ID: 15106966373. Thanksss a lot!
