### ISSUE TITLE
dataset ZHZisZZ/imdb_preference

### ISSUE THREAD

**Issue by Young-Zhen** [ZHZisZZ/weak-to-strong-search#3]
Hi,
This is actually a remarkable work in the fild of LLM alignment, thanks for your marvelous work!
But I got some problems when reimplementing the results of controlled sentiment generation, that is, the dataset 'ZHZisZZ/imdb_preference' is missing so the fine-tuning of base gpt-2 models is not easy to carry out. Therefore, I wonder if you mind sharing the dataset with a google drive link or baidu netdisk link? I believe it will, to some extent, help me and other people to follow this work. 
Finally, this is absolutely a pioneering work in my view. Thanks for your excellent work and the contributions to the open-source comunity!

**Comment by ZHZisZZ** [comment]
This dataset is actually publically available: https://huggingface.co/datasets/ZHZisZZ/imdb_preference.

If you run the [training script](https://github.com/ZHZisZZ/weak-to-strong-search/blob/main/scripts/controlled_sentiment_generation/dpo.py), the dataset will be automatically downloaded.

**Comment by Young-Zhen** [comment]
sorry, I have found the dataset in hugging face right now. very sorry to bother you!
